# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main  # This will trigger the action when code is pushed to the main branch

env:
  AZURE_WEBAPP_NAME: newstaggingapp  # Correct Azure Web App name
  WORKING_DIRECTORY: '.'             # Path to your app's root directory
  PYTHON_VERSION: '3.10'             # Python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v2  # Use v2 to avoid deprecation warnings
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install dependencies
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Azure login
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this secret is set correctly

      # Configure Azure Web App settings
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          general-settings-json: '{"windowsFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}'  # For Windows-based apps

      # Deploy to Azure Web App
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Ensure the publish profile secret is set correctly
          package: ${{ env.WORKING_DIRECTORY }}

      # Logout of Azure
      - name: Logout of Azure
        run: |
          az logout
